---
title: "Cut and Run analysis for Christopher Douse"
author: "Anna V. Protasio"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
---

This project looks at differential binding of wild type TASOR (D3 and WTT) and modified versions of this protein: a mutated version (muT) and a KO version (TKO).

Question: Are there any differences between D3 and WTT? If yes, how do they differ?

Samples have been generated with a modifed version of the Cut&Run protocol, published in <insert publication record> and modified as described in Material and Methods of our paper (insert bioRxive link to paper). The Cut&Run protocol produced chip-seq like reads (albeit smaller and with a much better resolution) which we can then use to call in *peaks* and to call either *presence and abscence* or *differential binding*. 

We implement the use of RUVseq <enter citation> to remove unwanted variation in the Chipseq data. This has been previously been done in <enter Perixoto citation>. 


